version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
      - API_PREFIX=${API_PREFIX}
      - NODE_ENV=${NODE_ENV}
      - TYPEORM_SYNCHRONIZE=${TYPEORM_SYNCHRONIZE}
      - TYPEORM_ENTITIES=${TYPEORM_ENTITIES}
      - TYPEORM_ENTITIES_DIR=${TYPEORM_ENTITIES_DIR}
      - SWAGGER_TITLE=${SWAGGER_TITLE}
      - SWAGGER_DESCRIPTION=${SWAGGER_DESCRIPTION}
      - SWAGGER_VERSION=${SWAGGER_VERSION}
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
